<?php

namespace App\Libraries;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Color;

/**
 * ExcelService — generates .xlsx files from structured sheet data.
 *
 * Sheet data format (each sheet is an array):
 *   ['name' => 'Sheet1', 'headers' => ['Col A', 'Col B'], 'rows' => [['val1','val2'], ...]]
 *
 * Theme: navy header (#1C2B3A) with white bold text, gold accents (#F59E0B),
 *        alternating white/light-grey rows.
 */
class ExcelService
{
    private const HEADER_BG   = 'FF1C2B3A';  // navy
    private const HEADER_FG   = 'FFFFFFFF';  // white
    private const ACCENT      = 'FFF59E0B';  // gold
    private const ROW_ALT     = 'FFF3F4F6';  // light grey for alternating rows
    private const BORDER_CLR  = 'FFD1D5DB';  // subtle border

    /**
     * Generate a .xlsx file and return its temp path.
     *
     * @param  string $spreadsheetTitle  Document title (shown in Office properties)
     * @param  array  $sheets            Each: ['name'=>…, 'headers'=>[…], 'rows'=>[[…],…]]
     * @return string                    Absolute path to the generated .xlsx file
     */
    public function generate(string $spreadsheetTitle, array $sheets): string
    {
        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setTitle($spreadsheetTitle)
            ->setCreator('Mosbat AI')
            ->setDescription('Generated by Mosbat AI');

        // Remove the default blank sheet
        $spreadsheet->removeSheetByIndex(0);

        foreach ($sheets as $i => $sheetData) {
            $ws = $spreadsheet->createSheet($i);
            $ws->setTitle($this->sanitizeSheetName($sheetData['name'] ?? ('Sheet' . ($i + 1))));
            $this->populateSheet($ws, $sheetData['headers'] ?? [], $sheetData['rows'] ?? []);
        }

        $spreadsheet->setActiveSheetIndex(0);

        $path = sys_get_temp_dir() . DIRECTORY_SEPARATOR . uniqid('xlsx_') . '.xlsx';
        $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
        $prev = error_reporting(E_ALL & ~E_WARNING & ~E_NOTICE & ~E_DEPRECATED);
        $writer->save($path);
        error_reporting($prev);

        return $path;
    }

    private function populateSheet($ws, array $headers, array $rows): void
    {
        $colCount = max(count($headers), empty($rows) ? 0 : max(array_map('count', $rows)));
        if ($colCount === 0) return;

        // ── Header row ────────────────────────────────────────────────────
        foreach ($headers as $c => $header) {
            $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($c + 1);
            $ws->setCellValue($colLetter . '1', $header);
        }

        $lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($colCount);
        $headerRange = 'A1:' . $lastCol . '1';

        $ws->getStyle($headerRange)->applyFromArray([
            'font' => [
                'bold'  => true,
                'color' => ['argb' => self::HEADER_FG],
                'size'  => 11,
                'name'  => 'Calibri',
            ],
            'fill' => [
                'fillType'   => Fill::FILL_SOLID,
                'startColor' => ['argb' => self::HEADER_BG],
            ],
            'alignment' => [
                'vertical'   => Alignment::VERTICAL_CENTER,
                'horizontal' => Alignment::HORIZONTAL_LEFT,
                'wrapText'   => false,
            ],
            'borders' => [
                'bottom' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color'       => ['argb' => self::ACCENT],
                ],
            ],
        ]);
        $ws->getRowDimension(1)->setRowHeight(22);

        // ── Data rows ─────────────────────────────────────────────────────
        foreach ($rows as $r => $row) {
            $rowNum = $r + 2;
            $isAlt  = ($r % 2 === 1);

            foreach ($row as $c => $value) {
                $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($c + 1);
                $ws->setCellValue($colLetter . $rowNum, $this->castValue($value));
            }

            if ($colCount > 0) {
                $dataRange = 'A' . $rowNum . ':' . $lastCol . $rowNum;
                $ws->getStyle($dataRange)->applyFromArray([
                    'font' => [
                        'name' => 'Calibri',
                        'size' => 10,
                    ],
                    'fill' => $isAlt ? [
                        'fillType'   => Fill::FILL_SOLID,
                        'startColor' => ['argb' => self::ROW_ALT],
                    ] : [
                        'fillType' => Fill::FILL_NONE,
                    ],
                    'alignment' => [
                        'vertical' => Alignment::VERTICAL_CENTER,
                    ],
                    'borders' => [
                        'bottom' => [
                            'borderStyle' => Border::BORDER_THIN,
                            'color'       => ['argb' => self::BORDER_CLR],
                        ],
                    ],
                ]);
                $ws->getRowDimension($rowNum)->setRowHeight(18);
            }
        }

        // ── Auto-size columns ─────────────────────────────────────────────
        for ($c = 1; $c <= $colCount; $c++) {
            $colLetter = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($c);
            $ws->getColumnDimension($colLetter)->setAutoSize(true);
        }

        // ── Freeze header row ─────────────────────────────────────────────
        $ws->freezePane('A2');

        // ── Enable auto-filter ────────────────────────────────────────────
        if (!empty($rows)) {
            $lastRow = count($rows) + 1;
            $ws->setAutoFilter('A1:' . $lastCol . $lastRow);
        }
    }

    /** Cast a string value to int/float if it looks like a plain number. */
    private function castValue(string $value): string|int|float
    {
        $v = trim($value);
        if ($v === '') return '';
        // Pure integer (no currency/percent symbols)
        if (preg_match('/^-?\d+$/', $v)) return (int) $v;
        // Pure decimal
        if (preg_match('/^-?\d+\.\d+$/', $v)) return (float) $v;
        return $value;
    }

    private function sanitizeSheetName(string $name): string
    {
        // Excel sheet names max 31 chars, no special chars
        $name = preg_replace('/[:\\\\\/\?\*\[\]]/', '', $name);
        return mb_substr(trim($name) ?: 'Sheet', 0, 31);
    }
}
